spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      format_sql: true
      generate-ddl: true
    properties:
      database-platform: org.hibernate.dialect.MariaDB106Dialect

  flyway:
    enabled: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE;
    username: user
    password:

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql: trace

  file:
    name: ./logs/stock_local.log
