spring:
  config:
    activate:
      on-profile: prod

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      database-platform: org.hibernate.dialect.MariaDB106Dialect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:13306/securities
    username: root
    password: 1q2w3e4r!!

  flyway:
    enabled: true
    locations: classpath:/db/migration
    sql-migration-suffixes: sql
    baseline-version: 0
    baseline-on-migrate: true

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: info

  file:
    name: ./logs/stock_prod.log